project:
  type: website
  output-dir: _site

website:
  title: "Jack Quach"
  navbar:
    right:
      - href: index.qmd
        text: About Me
      - research.qmd
      - apps.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    fontsize: 1.1em

editor: visual

